### ISSUE TITLE
`vm/solution.sh`: error

### ISSUE THREAD

**Issue by evandrix** [fwenzel/synacor-challenge#2]
Running thru `vm/solution.sh` to get an idea of what all this is about, leads to a crash, as follows:

```
== Synacor Headquarters ==
You stand in the lobby of what appears to be a really fun place to work!  Sadly, there doesn't seem to be anyone around at the moment, so you make a note to call them later.  The bookshelf here looks like it might have something interesting in it, though.

Things of interest here:
- business card
- strange book

There is 1 exit:
- outside

What do you do?


Taken.

What do you do?


Taken.

What do you do?
Maintenance command: fix_teleporter OK

enter 'use teleporter' next.


A strange, electronic voice is projected into your mind:

  "Unusual setting detected!  Starting confirmation process!  Estimated time to completion: 1 billion years."

Traceback (most recent call last):
  File "vm/vm.py", line 342, in <module>
    main()
  File "vm/vm.py", line 335, in main
    vm.run()
  File "vm/vm.py", line 238, in run
    self.execute()
  File "vm/vm.py", line 217, in execute
    raise NotImplementedError('Opcode %s not implemented.' % op)
NotImplementedError: Opcode 32769 not implemented.
```

**Comment by fwenzel** [comment]
Ooo ugly! This might mean I have not solved that particular part of the puzzle correctly.
